"""Settings: defaults, budgets, branding, user/api tokens, delete requests."""
from __future__ import annotations

from pydantic import BaseModel
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.config import settings
from app.core.audit import record
from app.core.settings_service import get_setting, set_setting
from app.db import get_session
from app.models.settings_meta import SettingKV

router = APIRouter(prefix="/settings", tags=["settings"])


def _all(db):
    return {
        "daily_email_cap": get_setting(db, "defaults.daily_email_cap", settings.default_daily_email_cap),
        "daily_call_cap": get_setting(db, "defaults.daily_call_cap", settings.default_daily_call_cap),
        "send_window": get_setting(db, "defaults.send_window", {"start": "09:00", "end": "18:00", "days": ["mon","tue","wed","thu","fri"]}),
        "warm_up_schedule": get_setting(db, "defaults.warm_up_schedule", {"mode": "ramp", "start": 5, "days": 21, "target": 20}),
        "followup_delay_days": get_setting(db, "defaults.followup_delay_days", 4),
        "approval_mode": get_setting(db, "defaults.approval_mode", "manual"),
        "bounce_tolerance": get_setting(db, "compliance.bounce_tolerance", settings.bounce_rate_pause_threshold),
        "complaint_tolerance": get_setting(db, "compliance.complaint_tolerance", settings.spam_complaint_pause_threshold),
        "budgets": {
            "places": get_setting(db, "budget.places.monthly_cap", 1000.0),
            "llm": get_setting(db, "budget.llm.monthly_cap", 500.0),
            "voice": get_setting(db, "budget.voice.monthly_cap", 0.0),
            "email": get_setting(db, "budget.email.monthly_cap", 100.0),
        },
        "branding": {
            "sender_name": get_setting(db, "branding.sender_name", settings.sender_name),
            "sender_email": get_setting(db, "branding.sender_email", settings.sender_email),
            "physical_address": get_setting(db, "branding.physical_address", settings.sender_physical_address),
            "demo_banner": get_setting(db, "branding.demo_banner", "Free demo site generated by LeadForge"),
            "unsubscribe_text": get_setting(db, "branding.unsubscribe_text", "You are receiving this because we found your business online. Click here to unsubscribe."),
        },
        "tokens": {
            "auth_tokens": [t for t in settings.token_list()],
            "admin_tokens": [t for t in settings.admin_token_list()],
        },
    }


def _serialize_campaign_defaults_only(db):  # pragma: no cover - helper
    return _all(db)


@router.get("")
def get_settings(db: Session = Depends(get_session)):
    return _all(db)


class SettingsUpdate(BaseModel):
    values: dict


@router.patch("")
def update_settings(payload: SettingsUpdate, db: Session = Depends(get_session)):
    values = payload.values
    mapping = {
        "daily_email_cap": "defaults.daily_email_cap",
        "daily_call_cap": "defaults.daily_call_cap",
        "send_window": "defaults.send_window",
        "warm_up_schedule": "defaults.warm_up_schedule",
        "followup_delay_days": "defaults.followup_delay_days",
        "approval_mode": "defaults.approval_mode",
        "bounce_tolerance": "compliance.bounce_tolerance",
        "complaint_tolerance": "compliance.complaint_tolerance",
        "demo_banner": "branding.demo_banner",
        "unsubscribe_text": "branding.unsubscribe_text",
    }
    for k, v in values.items():
        dbkey = mapping.get(k)
        if dbkey:
            set_setting(db, dbkey, v)
    # budget map
    budgets = values.get("budgets")
    if isinstance(budgets, dict):
        for kk, vv in budgets.items():
            set_setting(db, "budget." + kk + ".monthly_cap", vv)
    branding = values.get("branding")
    if isinstance(branding, dict):
        for kk, vv in branding.items():
            set_setting(db, "branding." + kk, vv)
    record(db, action="settings_updated", detail={"keys": list(values.keys())})
    return _all(db)


class TokenRequest(BaseModel):
    token: str = ""
    label: str = ""


@router.get("/tokens")
def list_tokens(db: Session = Depends(get_session)):
    return {
        "auth_tokens": [{"token": t, "admin": t in settings.admin_token_list()} for t in settings.token_list()],
    }


# data deletion requests (GDPR/PDPL-style)
class DeleteRequest(BaseModel):
    email: str
    reason: str = "data deletion request"


@router.post("/delete-request")
def create_delete_request(payload: DeleteRequest, db: Session = Depends(get_session)):
    from app.core.suppression import SuppressionService
    if "@" in payload.email:
        svc = SuppressionService(db)
        svc.add("email", payload.email.lower().strip(), reason=payload.reason)
        svc.add("domain", payload.email.split("@")[-1].lower().strip(), reason=payload.reason)
    record(db, action="data_delete_request", detail={"email": payload.email, "reason": payload.reason})
    return {"requested": True}
