from app.models.base import GUID

"""dashboard_upgrade

Revision ID: 3cbd6607908a
Revises: 
Create Date: 2026-10-07 09:00:28.212391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3cbd6607908a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer().with_variant(sa.BigInteger(), 'postgresql'), autoincrement=True, nullable=False),
    sa.Column('lead_id', GUID(length=36), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('area_radius_km', sa.Float(), nullable=True),
    sa.Column('categories', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.Column('lead_source', sa.String(length=16), nullable=False),
    sa.Column('daily_email_cap', sa.Integer(), nullable=False),
    sa.Column('daily_call_cap', sa.Integer(), nullable=False),
    sa.Column('max_leads_per_run', sa.Integer(), nullable=True),
    sa.Column('send_window', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('warm_up_schedule', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('followup_delay_days', sa.Integer(), nullable=False),
    sa.Column('approval_mode', sa.String(length=16), nullable=False),
    sa.Column('cron_schedule', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo_projects',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('base_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_secrets',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('is_set', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('suppression_list',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_suppression_kind_value')
    )
    op.create_table('leads',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('campaign_id', GUID(length=36), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_place_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('has_website', sa.Boolean(), nullable=False),
    sa.Column('raw_website', sa.Text(), nullable=True),
    sa.Column('contact_type', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_place_id', name='uq_leads_source_place')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)

    op.create_table('calls',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('lead_id', GUID(length=36), nullable=False),
    sa.Column('provider_call_id', sa.Text(), nullable=True),
    sa.Column('dnc_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_disclosed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_consent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('lead_id', GUID(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'kind', 'value', name='uq_contacts_lead_kind_value')
    )
    op.create_table('demo_sites',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('lead_id', GUID(length=36), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=True),
    sa.Column('html_path', sa.Text(), nullable=True),
    sa.Column('preview_url', sa.Text(), nullable=True),
    sa.Column('deploy_status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('lead_id', GUID(length=36), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', GUID(length=36), nullable=False),
    sa.Column('lead_id', GUID(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('sequence_step', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('inbound_content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=False),
    sa.Column('consent_token', sa.String(length=128), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('lead_id', GUID(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('services', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('selling_points', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('brand', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('raw_inputs', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_table('messages')
    op.drop_table('jobs')
    op.drop_table('demo_sites')
    op.drop_table('contacts')
    op.drop_table('calls')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_status'))

    op.drop_table('leads')
    op.drop_table('suppression_list')
    op.drop_table('settings')
    op.drop_table('integration_secrets')
    op.drop_table('demo_projects')
    op.drop_table('campaigns')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
